name: Daily Market Data Crawler

on:
  schedule:
    - cron: '0 1 * * 1-5'  # 每个工作日（周一到周五）的 UTC 1:00 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Microsoft Edge
      run: |
        # Add Microsoft repository and install Edge
        wget https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main"
        sudo apt-get update
        sudo apt-get install -y microsoft-edge-stable
    
    - name: Install latest Edge WebDriver
      run: |
        # Get the latest stable version of Edge WebDriver
        LATEST_VERSION=$(curl -s https://msedgedriver.azureedge.net/LATEST_STABLE)
        echo "Using latest stable Edge WebDriver version: $LATEST_VERSION"
        
        # Download and install the latest stable version of Edge WebDriver
        curl -L -o edgedriver.zip "https://msedgedriver.azureedge.net/${LATEST_VERSION}/edgedriver_linux64.zip"
    
        # Check if the download was successful
        if [ $? -ne 0 ]; then
          echo "Failed to download Edge WebDriver"
          exit 1
        fi
    
        # Unzip and install Edge WebDriver
        unzip edgedriver.zip
        chmod +x msedgedriver
        sudo mv msedgedriver /usr/local/bin/
    
        # Clean up downloaded zip file
        rm edgedriver.zip
    
    - name: Run crawler with Edge
      env:
        LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
      run: python crawler.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add market_data.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update market data" && git push)
