name: Daily Market Data Crawler

on:
  schedule:
    - cron: '0 9 * * 1-5'  # 每个工作日（周一到周五）的 UTC 1:00 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}  # 使用PAT進行checkout
        fetch-depth: 0  # 獲取所有歷史記錄，以便進行合併
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # 使用Python 3.12
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Google Chrome
      run: |
        CHROME_URL="https://storage.googleapis.com/chrome-for-testing-public/132.0.6834.159/linux64/chrome-linux64.zip"
        sudo apt-get update
        
        echo "Downloading Google Chrome from: $CHROME_URL"
        curl -L -o chrome.zip "$CHROME_URL"
        
        if [ $? -ne 0 ]; then
          echo "Failed to download Google Chrome"
          exit 1
        fi

        unzip chrome.zip
        chmod +x chrome-linux64/chrome
        sudo mv chrome-linux64/chrome /usr/local/bin/
        
        if [ -d "chrome-linux64" ]; then
          rm -r chrome-linux64
        fi
        rm chrome.zip
        
    
    - name: Install ChromeDriver
      run: |
        CHROMEDRIVER_URL="https://storage.googleapis.com/chrome-for-testing-public/132.0.6834.159/linux64/chromedriver-linux64.zip"
        echo "Downloading ChromeDriver from: $CHROMEDRIVER_URL"
        curl -L -o chromedriver.zip "$CHROMEDRIVER_URL"
        
        if [ $? -ne 0 ]; then
          echo "Failed to download ChromeDriver"
          exit 1
        fi
        
        unzip chromedriver.zip
        chmod +x chromedriver-linux64/chromedriver
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
        rm -r chromedriver.zip chromedriver-linux64
    
    - name: Install fonts
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-noto-cjk
    
    - name: Run crawler with Chrome
      env:
        LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
      run: python crawler.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add market_data.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update market data")
        git pull --rebase  # 拉取並重新應用本地更改
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}  # 使用PAT進行推送
