name: Daily Market Data Crawler

on:
  schedule:
    - cron: '0 1 * * 1-5'  # 每个工作日（周一到周五）的 UTC 1:00 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
    - name: Install ChromeDriver
      run: |
        # 指定稳定的ChromeDriver版本
        CHROMEDRIVER_VERSION="130.0.6723.58"  # 更新为与Chrome 130兼容的版本
        echo "Using ChromeDriver version: $CHROMEDRIVER_VERSION"
        
        # 下载并安装指定版本的ChromeDriver
        curl -L -o chromedriver.zip "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
    
        # 检查下载是否成功
        if [ $? -ne 0 ]; then
          echo "Failed to download ChromeDriver"
          exit 1
        fi
    
        # 解压缩并安装ChromeDriver
        unzip chromedriver.zip
        chmod +x chromedriver
        sudo mv chromedriver /usr/local/bin/
    
        # 清理下载的zip文件
        rm chromedriver.zip
    
    - name: Run crawler
      env:
        LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
      run: python crawler.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add market_data.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update market data" && git push)
